# Generated by Django 3.2 on 2021-04-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_row', models.IntegerField()),
                ('dataset', models.CharField(max_length=20)),
                ('point', models.CharField(max_length=20)),
                ('client_id', models.IntegerField()),
                ('client_name', models.CharField(max_length=45)),
            ],
        ),
    ]
